project_id = "volttrade-erp"

[functions.seed-demo-data]
verify_jwt = true

[functions.submit-schedule]
verify_jwt = true

[functions.import-dso-reads]
verify_jwt = false

[functions.link-consumer-pod]
verify_jwt = true

[functions.admin-invite-user]
verify_jwt = true

[functions.admin-invite-consumer]
verify_jwt = true
[functions.validate-readings]
verify_jwt = true
