import js from "@eslint/js";
import globals from "globals";
import reactHooks from "eslint-plugin-react-hooks";
import reactRefresh from "eslint-plugin-react-refresh";
import tseslint from "typescript-eslint";

export default tseslint.config(
  // src/integrations/supabase/* is auto-generated by the platform and is
  // rewritten wholesale on every regeneration — lint fixes there do not
  // survive, so it is excluded rather than repeatedly re-patched.
  { ignores: ["dist", "src/integrations/supabase/client.ts", "src/integrations/supabase/types.ts", "src/integrations/supabase/previewAuthStorage.ts"] },
  {
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
    files: ["**/*.{ts,tsx}"],
    languageOptions: {
      ecmaVersion: 2020,
      globals: globals.browser,
    },
    plugins: {
      "react-hooks": reactHooks,
      "react-refresh": reactRefresh,
    },
    rules: {
      ...reactHooks.configs.recommended.rules,
      "react-refresh/only-export-components": ["warn", { allowConstantExport: true }],
      "@typescript-eslint/no-unused-vars": "off",

      // 2026-09-03 (audit). `bunx eslint .` reported 638 errors, 620 of them
      // no-explicit-any, and the CI gate had therefore never once passed — a
      // gate everyone learns to ignore protects nothing. These two are now
      // warnings so the gate blocks on genuine errors (unreachable code, empty
      // blocks, banned ts-comments, require() in ESM) while the backlog stays
      // visible in the output. Promote them back to "error" as the counts
      // reach zero; do not silence them with "off".
      //
      // no-explicit-any is a backlog, not a policy: new code should be typed.
      // The audit's own additions (src/lib/paginate.ts, xlsxIo.ts,
      // _shared/paginate.ts, _shared/auth.ts, edge-auth.test.ts) contain no
      // `any` at all.
      "@typescript-eslint/no-explicit-any": "warn",
      "react-hooks/exhaustive-deps": "warn",
    },
  },
);
